# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20170206_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
            options={
                'ordering': ('path',),
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='fotos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Produto'),
        ),
    ]
