# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20170817_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
    ]
