# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_auto_20170818_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ['path']},
        ),
        migrations.AlterField(
            model_name='foto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='rest_api.Produto'),
        ),
        migrations.AlterUniqueTogether(
            name='foto',
            unique_together=set([('produto', 'path')]),
        ),
    ]
