# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_auto_20170818_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='thumb',
            field=models.CharField(default='images/portfolio/2.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
