# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_auto_20170824_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Produto', verbose_name='Produto'),
        ),
    ]
